import {Link} from 'react-router-dom';
import {AlertTriangle,ArrowRight,BookOpen,BrainCircuit,Building2,CheckCircle2,Database,Eye,FileSearch,Globe2,Layers,Lock,Network,Scale,ShieldCheck,Truck,UserCheck} from 'lucide-react';
import {Card} from '../../components/common/UI';
export {Problem,Product,Network as Participants,Contact} from '../v3/V3Marketing';

const layers=[
  ['1','Commercial transaction','Buyer, seller, product, quantity, price, delivery and payment records.','UN/CEFACT Buy-Ship-Pay'],
  ['2','Cross-border data','Goods, parties, consignments, declarations, permits and supporting documents.','WCO Data Model'],
  ['3','Contract responsibility','Who arranges carriage, insurance, clearance, delivery and payment.','Sales contract + Incoterms 2020'],
  ['4','Country procedure','The actual customs, permit, product-control and cargo systems for each jurisdiction.','ICEGATE · ACE · TradeNet · ICS/BICON'],
  ['5','Product requirements','Mandatory regulations, buyer specifications, testing, conformity and inspection basis.','Product and use-case specific'],
  ['6','AI control','What AI may read, extract, recommend and never decide.','ISO/IEC 42001 · NIST AI RMF references']
];

const countries=[
  {name:'India',system:'ICEGATE / I4C',what:'Tariff, policy, duty and Partner Government Agency information for Indian customs workflows.',ai:'Prepare candidate data, compare documents and flag likely agency or policy checks.',human:'Exporter and authorized customs professionals confirm and submit.'},
  {name:'United States',system:'ACE',what:'The US electronic Single Window for manifests, cargo release, exports and Partner Government Agency data.',ai:'Prepare filing data, compare descriptions and identify missing or conflicting fields.',human:'Importer, exporter, broker and relevant specialists remain responsible.'},
  {name:'Singapore',system:'TradeNet',what:'Permit applications and controlled-item requirements connected to Competent Authorities.',ai:'Identify possible HS and authority pathways, then assemble supporting evidence.',human:'The declarant and competent authorities determine the actual outcome.'},
  {name:'Australia',system:'ICS + BICON',what:'Cargo reporting and clearance status, plus biosecurity and food-safety import conditions.',ai:'Map possible scenarios, ask qualifying questions and monitor official status.',human:'Importers, brokers and government officers make decisions.'}
];

const officialSources=[
  ['WCO Data Model','https://www.wcoomd.org/DataModel'],
  ['UN/CEFACT Buy-Ship-Pay','https://unece.org/trade/documents/2019/08/brs-buy-ship-pay-reference-data-model-bsp-rdm'],
  ['WTO Trade Facilitation Agreement','https://www.wto.org/english/docs_e/legal_e/tfa_e.htm'],
  ['UNCITRAL MLETR','https://uncitral.un.org/en/texts/ecommerce/modellaw/electronic_transferable_records'],
  ['ICC Incoterms 2020','https://iccwbo.org/business-solutions/incoterms-rules/incoterms-2020/'],
  ['India ICEGATE / I4C','https://www.icegate.gov.in/Webappl/home'],
  ['US CBP ACE','https://www.cbp.gov/trade/automated/how-to-use-ace'],
  ['Singapore TradeNet controlled items','https://www.customs.gov.sg/doing-business/quick-links-for-traders/tradenet/competent-authorities-requirements-for-controlled-items/competent-authorities-requirements-for-controlled-items-overview/'],
  ['Australia Integrated Cargo System','https://www.abf.gov.au/help-and-support/ics/integrated-cargo-system-%28ics%29'],
  ['Australia BICON','https://bicon.agriculture.gov.au/'],
  ['ISO/IEC 42001','https://www.iso.org/standard/42001'],
  ['NIST AI Risk Management Framework','https://www.nist.gov/itl/ai-risk-management-framework']
];

export function Home(){return <main className="v4"><section className="v4hero"><div><span className="v4eyebrow">ORCHESTRATE TRADE TRANSACTIONS</span><h1>See the transaction.<br/><em>See the rules.</em><br/>See who decides.</h1><p>ForgeBridge turns scattered documents and partner updates into one traceable trade record. It summarizes the facts people need, attaches the applicable rule sources, limits what AI may scan and stops at every legal, technical, commercial or financial decision.</p><div className="actions"><Link className="btn" to="/demo">Open the visual V4 demo <ArrowRight/></Link><Link className="btn ghost" to="/rules">Explore the rules map</Link></div><p className="v4note">The product does not invent an international procedure. It maps each transaction to recognized data models, contracts, country systems, product requirements and named authorities.</p></div><div className="v4stack"><span>ONE TRANSACTION RECORD</span>{layers.map(([n,h,,source])=><div key={n}><b>{n}</b><span><strong>{h}</strong><small>{source}</small></span></div>)}<p>AI works above verified sources and below accountable people.</p></div></section>
<section className="v4section"><div className="v4head"><span>WHAT CHANGED IN V4</span><h2>Documents become visible evidence, not hidden attachments.</h2><p>A participant should not open a 40-page document to learn the quantity, delivery date, inspection result or release blocker. V4 displays approved variables directly and retains the exact source behind each value.</p></div><div className="v4beforeafter"><Card><h3>Before</h3>{['Commercial Invoice.pdf','Packing List v2.xlsx','Inspection Report.pdf','Broker email thread','Bank confirmation.pdf'].map(x=><p key={x}>📎 {x}</p>)}</Card><ArrowRight/><Card className="after"><h3>Evidence summary</h3>{[['Quantity','400 units'],['Packages','20 pallets'],['Gross weight','8,420 kg'],['Inspection','Passed'],['Release blocker','None']].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}<small>Every field shows source, verification and visibility.</small></Card></div></section>
<section className="v4dark"><div className="v4head"><span>THE OPERATING MODEL</span><h2>Standards-aware. Evidence-backed. Human-controlled.</h2></div><div className="v4model"><Card><Database/><h3>Transaction model</h3><p>Common commercial and border concepts keep buyer, seller, goods, order, delivery and payment records connected.</p></Card><Card><BookOpen/><h3>Rules registry</h3><p>Each rule stores authority, jurisdiction, version, effective date, transaction relevance and review status.</p></Card><Card><FileSearch/><h3>Evidence layer</h3><p>Facts are extracted from approved files with page, row, version, confidence and verification state.</p></Card><Card><ShieldCheck/><h3>Decision gates</h3><p>AI prepares. Named people approve. Licensed and operational partners execute.</p></Card></div></section>
<section className="v4section"><div className="v4head"><span>FOUR-COUNTRY LEARNING SAMPLE</span><h2>The same transaction concept maps to different national systems.</h2><p>India, the United States, Singapore and Australia are used as learning examples—not as proof that four workflows represent the entire world.</p></div><div className="v4countries">{countries.map(c=><Card key={c.name}><span>{c.system}</span><h3>{c.name}</h3><p>{c.what}</p><div><b>AI placement</b><small>{c.ai}</small></div><div><b>Authority</b><small>{c.human}</small></div></Card>)}</div><Link className="textlink" to="/rules">Open the full visual rules map →</Link></section>
<section className="v4roles"><div><BrainCircuit/><span>AI PREPARES</span><h2>Read, structure, compare, summarize and monitor.</h2></div><div><UserCheck/><span>HUMANS APPROVE</span><h2>Price, engineering, quality, legal terms and release.</h2></div><div><Truck/><span>PARTNERS EXECUTE</span><h2>Inspection, freight, customs, banking and delivery.</h2></div></section>
<section className="v4cta"><span>VISUAL GUIDED DEMO</span><h2>Open the transaction and switch between evidence, rules and AI guardrails.</h2><p>Start anywhere or jump directly to the shipment-release stage to see how documents become visible, permission-controlled facts.</p><Link className="btn" to="/demo">Start V4 demo</Link></section></main>}

export function Rules(){return <main className="v4page"><span className="v4eyebrow">RULES MAP</span><h1>There is no single “IEEE for international trade.”</h1><p className="lead">A real transaction combines international reference models, commercial rules, national procedures, product requirements and organization-specific controls. ForgeBridge records the layers instead of pretending they are one universal checklist.</p><section className="v4rulelayers">{layers.map(([n,h,p,source])=><Card key={n}><b>{n}</b><div><span>{source}</span><h2>{h}</h2><p>{p}</p></div></Card>)}</section><section className="v4countrysection"><div className="v4head"><span>COUNTRY SYSTEMS</span><h2>Where AI sits in four national examples</h2></div><div className="v4countrytable"><div className="head"><b>Country</b><b>Official system</b><b>AI prepares</b><b>Responsible party decides</b></div>{countries.map(c=><div key={c.name}><strong>{c.name}</strong><span>{c.system}<small>{c.what}</small></span><span>{c.ai}</span><span>{c.human}</span></div>)}</div></section><section className="v4ruleprinciples"><Card><Scale/><h3>Reference model ≠ law</h3><p>UN/CEFACT and WCO models provide common information structures. A national law, regulation or authorized filing still controls the actual obligation.</p></Card><Card><Globe2/><h3>Country system ≠ product approval</h3><p>Customs clearance does not automatically prove that a product meets all technical, safety, labeling or conformity requirements.</p></Card><Card><CheckCircle2/><h3>Standard ≠ mandatory regulation</h3><p>A standard may be voluntary, contractually required or made mandatory by regulation. The transaction must record which one applies.</p></Card><Card><AlertTriangle/><h3>AI summary ≠ compliance decision</h3><p>The AI may show that evidence is present and rules were checked. It must not declare the shipment legally compliant.</p></Card></section><section className="v4sources"><div className="v4head"><span>OFFICIAL STARTING POINTS</span><h2>Sources used to design this learning prototype</h2><p>These links are starting points for a maintained rules registry. Licensed standards and professional interpretation may still be required.</p></div><div>{officialSources.map(([label,url])=><a href={url} target="_blank" rel="noreferrer" key={label}>{label}<ArrowRight/></a>)}</div></section></main>}

export function AI(){return <main className="v4page"><span className="v4eyebrow">AI PLACEMENT AND GUARDRAILS</span><h1>AI reads only what the stage requires.</h1><p className="lead">The safe architecture is not “connect the model to every company file.” Every run begins with a purpose, document allowlist, field allowlist, excluded data and blocked actions.</p><section className="v4aipipeline"><Card><Building2/><span>Approved sources</span><h3>Transaction files and official rule registry</h3><p>Only records belonging to the transaction, approved company knowledge and controlled official sources.</p></Card><ArrowRight/><Card><FileSearch/><span>Bounded AI</span><h3>Extract, compare, summarize and draft</h3><p>The model receives a stage-specific scan manifest and cannot expand its own access.</p></Card><ArrowRight/><Card><UserCheck/><span>Accountable decision</span><h3>Human or authorized partner</h3><p>The system stops before legal, technical, customs, quality, payment or shipment authority.</p></Card></section><section className="v4guardrails"><div className="v4head"><span>NON-NEGOTIABLE CONTROLS</span><h2>The AI control plane</h2></div><div>{[['Document allowlist','Read only approved files attached to the current transaction and stage.'],['Field allowlist','Extract only the fields required for the stated purpose.'],['Tenant isolation','Never retrieve another customer’s records.'],['Source provenance','Every factual output needs file, version and location.'],['Conflict escalation','Display contradictory values and block the dependent step.'],['Rule versioning','Store authority, edition, effective date and last review.'],['Role visibility','Shared summaries and restricted internal variables remain separate.'],['Named approval','High-risk decisions require a responsible person or partner.'],['Prompt-injection defense','Treat document instructions as untrusted content, not system commands.'],['Audit history','Record what was read, produced, corrected, approved and submitted.']].map(([h,p],i)=><Card key={h}>{i%2?<Lock/>:<ShieldCheck/>}<h3>{h}</h3><p>{p}</p></Card>)}</div></section><section className="v4cannot"><div><BrainCircuit/><h2>AI can say</h2><p>“Seven required fields are present. The HS classification is a candidate and needs customs-broker confirmation.”</p></div><div><AlertTriangle/><h2>AI cannot say</h2><p>“This shipment is legally compliant and cleared for export.”</p></div></section><Link className="btn" to="/demo">See the scan manifest inside the demo</Link></main>}
