export type Status='New'|'Saved'|'Declined'|'Draft'|'Internal Review'|'Sent'|'Negotiation'|'Won'|'Lost';
export interface Machine {id:string;name:string;quantity:number}
export interface Product {id:string;category:string;description:string;materials:string;moq:number;leadTime:number;price:string;currency:string;hsCode?:string}
export interface Certification {id:string;name:string;number:string;expires:string;status:'Approved'|'Expiring'}
export interface CommercialRules {minimumOrder:number;minimumMargin:number;approvalThreshold:number;incoterms:string[];paymentTerms:string}
export interface Manufacturer {name:string;tradingName:string;location:string;founded:number;employees:number;industry:string;processes:string[];materials:string[];markets:string[];monthlyCapacity:number;availableCapacity:number;machines:Machine[];products:Product[];certifications:Certification[];rules:CommercialRules}
export interface Buyer {id:string;alias:string;country:string;categories:string[];averageOrder:number;reliability:number;leadTime:number;certifications:string[]}
export interface RFQ {id:string;buyer:string;company:string;country:string;product:string;category:string;quantity:number;targetPrice:number;currency:string;destination:string;requiredDate:string;incoterm:string;certifications:string[];status:string;createdAt:string}
export interface Opportunity {id:string;rfqId:string;buyer:string;country:string;product:string;quantity:number;value:number;delivery:string;score:number;status:Status;risk:string;certifications:string[];saved:boolean;question?:string;declineReason?:string}
export interface QuoteCostBreakdown {material:number;manufacturing:number;tooling:number;inspection:number;packaging:number;inlandFreight:number;internationalFreight:number;insurance:number;duty:number;platformCommission:number;contingency:number;margin:number}
export interface Quote {id:string;opportunityId:string;product:string;buyer:string;quantity:number;currency:string;incoterm:string;paymentTerms:string;validity:string;notes:string;costs:QuoteCostBreakdown;status:Status;negotiationNote?:string;reason?:string}
export interface ShipmentMilestone {id:string;name:string;complete:boolean;date?:string}
export interface ComplianceDocument {id:string;name:string;status:'Missing'|'Draft'|'Ready'|'Expiring'|'Approved'}
export interface Order {id:string;rfqId:string;buyer:string;supplier:string;product:string;value:number;currency:string;destination:string;incoterm:string;mode:string;eta:string;payment:string;milestones:ShipmentMilestone[];documents:ComplianceDocument[];activity:string[]}
export interface MessageThread {id:string;subject:string;participant:string;unread:boolean;relatedId:string;messages:{id:string;sender:string;text:string;time:string;attachment?:string}[]}
export interface Notification {id:string;text:string;read:boolean}
export interface ContactSubmission {id:string;name:string;email:string;company:string;country:string;role:string;message:string}
export interface ManufacturerOnboardingDraft {step:number;fields:Record<string,string>;submitted:boolean;applicationId?:string}
export interface BuyerRFQDraft {step:number;fields:Record<string,string>;submitted:boolean}
export interface Settings {emailNotifications:boolean;currency:string;autoApprove:boolean;companySignature:string}
export interface AppState {manufacturer:Manufacturer;rfqs:RFQ[];opportunities:Opportunity[];quotes:Quote[];orders:Order[];messages:MessageThread[];contacts:ContactSubmission[];onboarding:ManufacturerOnboardingDraft;rfqDraft:BuyerRFQDraft;settings:Settings;notifications:Notification[]}
