import {Navigate,Route,Routes} from 'react-router-dom';
import {AppShell,PublicLayout} from '../components/layout/Shells';
import {About,Buyers,Contact,Home,HowItWorks,Industries,Manufacturers,WhatWeManage} from '../pages/marketing/Marketing';
import {Wizard} from '../pages/Wizards';
import {Analytics,FactoryProfile,Messages,OrderDetail,Orders,OpportunityDetail,Opportunities,Overview,QuoteBuilder,QuoteDetail,Quotes,Settings} from '../pages/manufacturer/Manufacturer';
import {BuyerMessages,BuyerOrder,BuyerOrders,BuyerOverview,BuyerRfqDetail,BuyerRfqs,Compare} from '../pages/buyer/Buyer';
import {DemoEntry,GuidedDemo} from '../pages/demo/Demo';
import {LeadsBuyers,OperationalList,Payments,ProductCatalog,Quality} from '../pages/manufacturer/Operations';
const NotFound=()=> <main className="publicpage"><span className="shippinglabel">404 · ROUTE NOT FOUND</span><h1>This shipment went to the wrong route.</h1><p className="lead">The page does not exist. Return to the public website or open the guided demo.</p><a className="btn" href="/">Return home</a></main>;
export default function App(){return <Routes>
 <Route element={<PublicLayout/>}><Route path="/" element={<Home/>}/><Route path="/how-it-works" element={<HowItWorks/>}/><Route path="/manufacturers" element={<Manufacturers/>}/><Route path="/buyers" element={<Buyers/>}/><Route path="/what-we-manage" element={<WhatWeManage/>}/><Route path="/about" element={<About/>}/><Route path="/industries" element={<Industries/>}/><Route path="/contact" element={<Contact/>}/><Route path="/demo" element={<DemoEntry/>}/><Route path="/submit-rfq" element={<Wizard buyer/>}/></Route>
 <Route path="/demo/factory" element={<GuidedDemo/>}/><Route path="/demo/buyer" element={<GuidedDemo buyer/>}/><Route path="/demo/manufacturer" element={<Navigate to="/demo/factory" replace/>}/><Route path="/start-exporting" element={<Navigate to="/demo/factory" replace/>}/>
 <Route path="/manufacturer" element={<AppShell/>}><Route index element={<Overview/>}/><Route path="profile" element={<FactoryProfile/>}/><Route path="products" element={<ProductCatalog/>}/><Route path="leads" element={<LeadsBuyers/>}/><Route path="opportunities" element={<Opportunities/>}/><Route path="opportunities/:id" element={<OpportunityDetail/>}/><Route path="quote-builder/:id" element={<QuoteBuilder/>}/><Route path="quotes" element={<Quotes/>}/><Route path="quotes/:id" element={<QuoteDetail/>}/><Route path="orders" element={<Orders/>}/><Route path="orders/:id" element={<OrderDetail/>}/><Route path="production" element={<OperationalList kind="Production"/>}/><Route path="quality" element={<Quality/>}/><Route path="documents" element={<OperationalList kind="Documents"/>}/><Route path="shipments" element={<OperationalList kind="Shipments"/>}/><Route path="payments" element={<Payments/>}/><Route path="compliance" element={<Navigate to="/manufacturer/documents" replace/>}/><Route path="buyers" element={<Navigate to="/manufacturer/leads" replace/>}/><Route path="messages" element={<Messages/>}/><Route path="analytics" element={<Analytics/>}/><Route path="settings" element={<Settings/>}/></Route>
 <Route path="/buyer" element={<AppShell buyer/>}><Route index element={<BuyerOverview/>}/><Route path="rfqs" element={<BuyerRfqs/>}/><Route path="rfqs/:id" element={<BuyerRfqDetail/>}/><Route path="compare/:id" element={<Compare/>}/><Route path="orders" element={<BuyerOrders/>}/><Route path="orders/:id" element={<BuyerOrder/>}/><Route path="messages" element={<BuyerMessages/>}/></Route><Route path="*" element={<NotFound/>}/>
 </Routes>}
