import {Link} from 'react-router-dom';
import {ArrowRight,BrainCircuit,Building2,CheckCircle2,ClipboardCheck,FileSearch,Handshake,PackageCheck,Route,ShieldCheck,Truck,WalletCards} from 'lucide-react';
import {Card} from '../../components/common/UI';

const problems=[
  ['Too much manual interpretation','Requests, specifications, quotes, purchase orders and inspection records arrive in different formats. People repeatedly read and re-enter the same facts.'],
  ['No shared transaction truth','Buyer, seller, forwarder, inspector, customs broker and bank each hold a different part of the transaction.'],
  ['Exceptions appear too late','Missing approvals, document conflicts, quality holds and payment conditions are often discovered only when they block shipment or payment.'],
  ['Margin disappears between systems','Freight, duties, inspection, rework, delays and currency assumptions are separated from the original commercial decision.']
];

const aiJobs=[
  ['Interpret', 'Read emails, catalogs, specifications, drawings, quotes, purchase orders and reports.'],
  ['Structure', 'Turn scattered information into one transaction record with sources, owners and required evidence.'],
  ['Check', 'Find missing fields, conflicting terms, expired records, risk conditions and blocked next steps.'],
  ['Prepare', 'Draft questions, comparisons, quotes, documents, updates and decision packs.'],
  ['Monitor', 'Watch due dates, approvals, partner milestones, delivery conditions and payment triggers.'],
  ['Explain', 'Show what changed, why the transaction is blocked and who must act next.']
];

const lifecycle=[
  ['1','Request','Buyer states what is needed. AI structures the request and identifies what is missing.'],
  ['2','Source','Approved suppliers, manufacturers or products are compared against the requirement.'],
  ['3','Quote','Commercial, technical, compliance and delivery assumptions are assembled for approval.'],
  ['4','Commit','Buyer and seller approve price, scope, terms, quality requirements and responsibilities.'],
  ['5','Execute','Production, documents, inspection and partner milestones are tracked against the agreement.'],
  ['6','Deliver','Freight and customs partners perform physical and regulated work. ForgeBridge monitors status and evidence.'],
  ['7','Settle','Delivery, acceptance, claims and payment conditions are reconciled until the transaction closes.']
];

export function Home(){return <main className="v3"><section className="v3hero"><div><span className="v3eyebrow">AI TRADE EXECUTION</span><h1>One transaction.<br/><em>From request to payment.</em></h1><p>ForgeBridge turns scattered trade documents, messages, approvals and partner updates into one traceable transaction. AI prepares the work. People approve commitments. Specialists execute regulated and physical tasks.</p><div className="actions"><Link className="btn" to="/demo">Run the guided transaction <ArrowRight/></Link><Link className="btn ghost" to="/problem">See the problem we solve</Link></div><p className="v3note">For importers, exporters, manufacturers, distributors and industrial buyers handling complex physical-goods transactions.</p></div><div className="v3record"><span>TRANSACTION FB-26041</span><h3>Industrial pump assemblies</h3><div className="v3flow"><b>I want this</b><i>→</i><b>Quote approved</b><i>→</i><b>Delivered</b><i>→</i><b>Paid</b></div>{[['Requirement','Complete'],['Supplier decision','Approved'],['Documents','12 of 14 ready'],['Partner milestone','Inspection booked'],['Payment condition','Deposit received']].map(x=><div className="v3row" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}<small>Every status links to its source, owner and next action.</small></div></section>
<section className="v3section"><div className="v3head"><span>THE PROBLEM</span><h2>Physical-goods trade is reconstructed manually across companies.</h2><p>A transaction can span sales, engineering, procurement, compliance, quality, freight, customs, banking and finance. Each team uses different records, so people spend time interpreting, copying, reconciling and chasing instead of moving the transaction forward.</p></div><div className="v3grid4">{problems.map(([h,p])=><Card key={h}><h3>{h}</h3><p>{p}</p></Card>)}</div></section>
<section className="v3dark"><div className="v3head"><span>WHAT FORGEBRIDGE DOES</span><h2>Creates a living transaction record.</h2><p>Not another replacement for ERP, CRM, freight, customs or banking software. ForgeBridge connects the information and decisions that move between them.</p></div><div className="v3lifecycle">{lifecycle.map(x=><div key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
<section className="v3section"><div className="v3head"><span>WHERE AI WORKS</span><h2>AI handles information work, not legal authority.</h2><p>The useful AI is not a chatbot attached to a dashboard. It continuously converts unstructured trade information into structured work for the right person.</p></div><div className="v3grid3">{aiJobs.map(([h,p],i)=><Card key={h}>{[<FileSearch/>,<BrainCircuit/>,<ShieldCheck/>,<ClipboardCheck/>,<Route/>,<CheckCircle2/>][i]}<h3>{h}</h3><p>{p}</p></Card>)}</div><Link className="textlink" to="/ai">See exactly what AI can and cannot do →</Link></section>
<section className="v3roles"><div><span>AI PREPARES</span><h2>Read, compare, draft, monitor and flag.</h2><p>AI can create structured requirements, draft questions, assemble cost inputs, compare records, prepare documents and summarize exceptions.</p></div><div><span>HUMANS APPROVE</span><h2>Price, scope, capacity, quality, terms and release.</h2><p>Named people remain responsible for commercial, technical, legal, quality and payment decisions.</p></div><div><span>PARTNERS EXECUTE</span><h2>Inspection, freight, customs, insurance and funds.</h2><p>Licensed and operational partners perform regulated and physical work. ForgeBridge records their evidence and status.</p></div></section>
<section className="v3section"><div className="v3head"><span>WHO IT SERVES</span><h2>Different businesses. The same fragmented transaction.</h2></div><div className="v3grid4">{[['Importers','Supplier coordination, landed cost, documents, customs and delivery.'],['Exporters','Buyer qualification, quotation, compliance, shipment and payment.'],['Manufacturers','Specifications, capacity, costing, quality evidence and order execution.'],['Industrial distributors','Sourcing, supplier comparison, replenishment, exceptions and customer delivery.']].map(([h,p],i)=><Card key={h}>{[<Building2/>,<Handshake/>,<PackageCheck/>,<Truck/>][i]}<h3>{h}</h3><p>{p}</p></Card>)}</div></section>
<section className="v3cta"><span>GUIDED DEMO · NO ACCOUNT REQUIRED</span><h2>Follow one transaction from “I want this” to “payment received.”</h2><p>The demo uses a broad industrial import-export transaction and shows AI preparation, human approvals and partner execution at every stage.</p><Link className="btn" to="/demo">Start the guided transaction</Link></section></main>}

export function Problem(){return <main className="v3page"><span className="v3eyebrow">FRAGMENTED TRADE EXECUTION</span><h1>The problem is not a lack of software.</h1><p className="lead">The problem is that no system holds a complete, continuously updated understanding of what was requested, agreed, completed, blocked, delivered and paid across all participants.</p><div className="v3grid2"><Card><h2>Today</h2>{['Email contains the request','Spreadsheet contains the quote','ERP contains the order','Quality system contains inspection','Forwarder portal contains freight','Broker system contains customs','Bank portal contains payment'].map(x=><p key={x}>— {x}</p>)}</Card><Card><h2>With ForgeBridge</h2>{['One transaction identity','One requirement record','One decision and approval trail','One evidence index','One exception queue','One view of partner status','One completion and payment record'].map(x=><p key={x}><CheckCircle2/> {x}</p>)}</Card></div><section className="v3plain"><h2>The measurable outcome</h2><p>Less repeated data entry. Faster decisions. Fewer missed conditions. Better margin visibility. Earlier exception detection. Clear ownership. Faster delivery and payment.</p></section></main>}

export function Product(){return <main className="v3page"><span className="v3eyebrow">THE PRODUCT</span><h1>A transaction orchestration and intelligence layer.</h1><p className="lead">ForgeBridge sits across the existing participants and systems. It does not replace every specialized tool. It makes the whole transaction understandable and executable.</p><div className="v3process">{lifecycle.map(x=><Card key={x[1]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p><small>Saved output: source-linked record, owner, status and next action.</small></Card>)}</div></main>}

export function AI(){return <main className="v3page"><span className="v3eyebrow">AI BOUNDARIES</span><h1>AI reduces coordination labor. It does not assume authority.</h1><div className="v3grid3"><Card><BrainCircuit/><h2>AI prepares</h2>{['Extracts requirements','Matches records','Finds conflicts','Drafts questions and documents','Monitors deadlines','Summarizes exceptions'].map(x=><p key={x}>✓ {x}</p>)}</Card><Card><ShieldCheck/><h2>Human approves</h2>{['Technical feasibility','Price and margin','Capacity and delivery','Contracts and payment terms','Inspection exceptions','Shipment or fund release'].map(x=><p key={x}>✓ {x}</p>)}</Card><Card><Truck/><h2>Partner executes</h2>{['Independent inspection','Freight movement','Customs filing','Cargo insurance','Escrow or banking','Final delivery'].map(x=><p key={x}>✓ {x}</p>)}</Card></div><section className="v3plain"><h2>How the AI works</h2><p>Document extraction reads files. Retrieval finds approved company records. Rules and normal code calculate money and enforce thresholds. Language models interpret text, compare context and draft explanations. Agents act only on defined events, within budgets and approval limits.</p></section></main>}

export function Network(){return <main className="v3page"><span className="v3eyebrow">PARTICIPANTS</span><h1>One transaction. Many responsible parties.</h1><p className="lead">ForgeBridge gives every participant the relevant view without pretending that one company performs every role.</p><div className="v3grid3">{[['Buyer','Defines need, approves offer, supplies information and confirms receipt.'],['Seller or manufacturer','Confirms capability, price, production, quality and commercial commitments.'],['ForgeBridge','Structures information, prepares work, routes approvals and monitors the complete transaction.'],['Inspector','Performs independent inspection and issues evidence.'],['Freight and customs partners','Move goods and complete regulated transport and clearance work.'],['Bank or payment provider','Verifies and moves funds under the agreed conditions.']].map(([h,p])=><Card key={h}><h2>{h}</h2><p>{p}</p></Card>)}</div></main>}

export function Contact(){return <main className="v3page"><span className="v3eyebrow">VALIDATION</span><h1>Tell us where your transactions break.</h1><p className="lead">This is a product-validation prototype. The useful feedback is not whether the website looks good. It is which handoff costs time, money or trust in real transactions.</p><Card><h2>Questions worth answering</h2>{['Which transaction step requires the most chasing?','Which records are repeatedly re-entered?','Which mistake causes the greatest financial loss?','Which decision would you never delegate to AI?','Which AI-prepared output would reduce hiring or workload?','Would you test ForgeBridge on one real transaction?'].map(x=><p key={x}>— {x}</p>)}</Card></main>}
