from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

from fastapi import Request
from pydantic import BaseModel
from starlette.responses import JSONResponse


class ErrorCode(StrEnum):
    REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED"
    REQUEST_PAYLOAD_TOO_LARGE = "REQUEST_PAYLOAD_TOO_LARGE"
    REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND"
    REQUEST_METHOD_NOT_ALLOWED = "REQUEST_METHOD_NOT_ALLOWED"
    REQUEST_CONFLICT = "REQUEST_CONFLICT"
    REQUEST_FORBIDDEN = "REQUEST_FORBIDDEN"
    RATE_LIMITED = "RATE_LIMITED"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    INTERNAL_UNEXPECTED_ERROR = "INTERNAL_UNEXPECTED_ERROR"

    AUTH_CSRF_FAILED = "AUTH_CSRF_FAILED"
    AUTH_ORIGIN_REJECTED = "AUTH_ORIGIN_REJECTED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED"
    AUTH_SESSION_REVOKED = "AUTH_SESSION_REVOKED"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_IDENTITY_CONFLICT = "AUTH_IDENTITY_CONFLICT"
    AUTH_RATE_LIMITED = "AUTH_RATE_LIMITED"

    VEHICLE_MODEL_PROVIDER_TIMEOUT = "VEHICLE_MODEL_PROVIDER_TIMEOUT"
    VEHICLE_MODEL_PROVIDER_UNAVAILABLE = "VEHICLE_MODEL_PROVIDER_UNAVAILABLE"
    VEHICLE_MODEL_PROVIDER_INVALID_RESPONSE = "VEHICLE_MODEL_PROVIDER_INVALID_RESPONSE"

    VIN_INVALID_FORMAT = "VIN_INVALID_FORMAT"
    VIN_CHECK_DIGIT_INVALID = "VIN_CHECK_DIGIT_INVALID"
    VIN_CRYPTO_UNAVAILABLE = "VIN_CRYPTO_UNAVAILABLE"
    VIN_PROVIDER_TIMEOUT = "VIN_PROVIDER_TIMEOUT"
    VIN_PROVIDER_UNAVAILABLE = "VIN_PROVIDER_UNAVAILABLE"
    VIN_PROVIDER_INVALID_RESPONSE = "VIN_PROVIDER_INVALID_RESPONSE"
    VIN_DECODE_FAILED = "VIN_DECODE_FAILED"
    VIN_DECODE_REQUIRED = "VIN_DECODE_REQUIRED"
    VIN_UNSUPPORTED_VEHICLE = "VIN_UNSUPPORTED_VEHICLE"

    USER_VEHICLE_NOT_FOUND = "USER_VEHICLE_NOT_FOUND"
    USER_VEHICLE_VIN_EXISTS = "USER_VEHICLE_VIN_EXISTS"
    USER_VEHICLE_ARCHIVED = "USER_VEHICLE_ARCHIVED"
    USER_VEHICLE_IDENTITY_UNVERIFIED = "USER_VEHICLE_IDENTITY_UNVERIFIED"

    REPAIR_SESSION_NOT_FOUND = "REPAIR_SESSION_NOT_FOUND"
    REPAIR_SESSION_ARCHIVED = "REPAIR_SESSION_ARCHIVED"
    REPAIR_SESSION_DEVICE_ID_INVALID = "REPAIR_SESSION_DEVICE_ID_INVALID"
    REPAIR_SESSION_IDEMPOTENCY_INVALID = "REPAIR_SESSION_IDEMPOTENCY_INVALID"
    REPAIR_SESSION_IDEMPOTENCY_CONFLICT = "REPAIR_SESSION_IDEMPOTENCY_CONFLICT"
    REPAIR_SESSION_LEASE_REQUIRED = "REPAIR_SESSION_LEASE_REQUIRED"
    REPAIR_SESSION_LEASE_HELD = "REPAIR_SESSION_LEASE_HELD"
    REPAIR_SESSION_STATE_CONFLICT = "REPAIR_SESSION_STATE_CONFLICT"
    REPAIR_SESSION_STATE_CORRUPT = "REPAIR_SESSION_STATE_CORRUPT"

    STORAGE_LOCATION_NOT_FOUND = "STORAGE_LOCATION_NOT_FOUND"
    FASTENER_NOT_FOUND = "FASTENER_NOT_FOUND"
    INVENTORY_ITEM_NOT_FOUND = "INVENTORY_ITEM_NOT_FOUND"
    OBSERVATION_NOT_FOUND = "OBSERVATION_NOT_FOUND"
    PHOTO_EVIDENCE_NOT_FOUND = "PHOTO_EVIDENCE_NOT_FOUND"
    PHOTO_ATTACHMENT_INVALID = "PHOTO_ATTACHMENT_INVALID"
    PHOTO_TOO_LARGE = "PHOTO_TOO_LARGE"
    PHOTO_MEDIA_TYPE_UNSUPPORTED = "PHOTO_MEDIA_TYPE_UNSUPPORTED"
    PHOTO_STORAGE_CORRUPT = "PHOTO_STORAGE_CORRUPT"
    PHOTO_CONTENT_UNAVAILABLE = "PHOTO_CONTENT_UNAVAILABLE"


class ErrorBody(BaseModel):
    code: str
    message: str
    request_id: str
    retryable: bool = False
    details: Any | None = None


class ErrorEnvelope(BaseModel):
    error: ErrorBody


@dataclass(slots=True)
class PartGraphError(Exception):
    code: ErrorCode | str
    message: str
    status_code: int
    retryable: bool = False
    details: Any | None = None
    headers: dict[str, str] | None = None

    def __str__(self) -> str:
        return self.message


def request_id(request: Request) -> str:
    return getattr(request.state, "request_id", "unknown")


def error_response(request: Request, error: PartGraphError) -> JSONResponse:
    payload = ErrorEnvelope(
        error=ErrorBody(
            code=str(error.code),
            message=error.message,
            request_id=request_id(request),
            retryable=error.retryable,
            details=error.details,
        )
    )
    return JSONResponse(
        status_code=error.status_code,
        content=payload.model_dump(mode="json", exclude_none=True),
        headers=error.headers,
    )
